server:
    port: 9090

spring:
    application:
        name: api-gateway

    security:
        oauth2:
            resourceserver:
                jwt:
                    jwk-set-uri: http://localhost:8082/.well-known/jwks.json

    cloud:
        gateway:
            mvc:
                routes:
                    - id: auth
                      uri: http://localhost:8082
                      predicates:
                          - Path=/auth/**
                    - id: publicaciones
                      uri: http://localhost:8081
                      predicates:
                          - Path=/publicaciones/**
                    - id: catalogo
                      uri: http://localhost:8083
                      predicates:
                          - Path=/catalogo/**
                    - id: notificaciones
                      uri: http://localhost:8084
                      predicates:
                          - Path=/notificaciones/**
