version: '3.7'
services:
  cockroachdb:
    image: cockroachdb/cockroach:v23.1.11
    container_name: cockroachdb
    command: start-single-node --insecure
    ports:
      - "26257:26257"  # Puerto para conexión JDBC
      - "8080:8080"    # Panel de administración web
    volumes:
      - cockroach-data:/cockroach/cockroach-data
  #Agrega este bloque debajo de cockroachdb
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  cockroach-data:
